### PR TITLE
Feed cleanup

### PR DESCRIPTION
**Pull request by mmitche**
Switch away from blob feeds.

### CODE REVIEW

**Comment by NikolaMilosavljevic** [comment]
Are all packages available in new feeds? It seems the validation is failing due to missing packages.

**Comment by mmitche** [comment]
> Are all packages available in new feeds? It seems the validation is failing due to missing packages.

Should be...I'll work my way through it.

**Comment by mmitche** [comment]
Pushing the winrt packages up to dotnet-eng.

**Pull request merged**
