### PR TITLE
Merging internal commits for release/6.0

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by RussKie** [comment]
@dotnet/dnceng 
```
##[error]pkg\windowsdesktop\bundle\Microsoft.WindowsDesktop.App.Bundle.bundleproj(0,0): error NU1102: (NETCORE_ENGINEERING_TELEMETRY=Restore) Unable to find package VS.Redist.Common.NetCore.SharedFramework.arm64.6.0 with version (= 6.0.11-servicing.22523.4)
  - Found 2193 version(s) in dotnet6-transport [ Nearest version: 6.0.11-servicing.22551.2 ]
  - Found 2 version(s) in dotnet5-transport [ Nearest version: 6.0.0-alpha.1.20420.3 ]
  - Found 0 version(s) in dotnet-eng
  - Found 0 version(s) in dotnet-public
  - Found 0 version(s) in dotnet-tools
  - Found 0 version(s) in dotnet5
  - Found 0 version(s) in dotnet6
```

**Comment by epananth** [comment]
Looks like this package was pushed only 30 mins ago

image

I will rerun this to see if it gets picked up

**Comment by RussKie** [comment]
@vseanreesermsft could you please resolve the MC? Thanks

**Comment by dreddy-work** [comment]
@vseanreesermsft , can you resolve conflict here?

**Pull request merged**
