### PR TITLE
Update branding on desktop servicing branch to 5.0.6.

### PR DESCRIPTION
**Pull request by dreddy-work**
Update branding to 5.0.6  in servicing branch.

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by dreddy-work** [comment]
@ryalanms , Did you see these failure earlier?

**Comment by ryalanms** [comment]
##[error]We stopped hearing from agent NetCorePublic-Pool 441. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610

@dreddy-work: This is an infrastructure issue.  Re-running should fix it.

**Review by ryalanms — APPROVED** [review]

**Comment by dreddy-work** [comment]
> ##[error]We stopped hearing from agent NetCorePublic-Pool 441. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
> 
> @dreddy-work: This is an infrastructure issue. Re-running should fix it.

@ryalanms , did re-run but failed again.

**Comment by ryalanms** [comment]
See https://status.dev.azure.com/_event/235403933.

**Comment by dreddy-work** [comment]
Merging with known infra failure.

**Pull request merged**
