### PR TITLE
Update build image in release/7.0

### PR DESCRIPTION
**Pull request by dreddy-work**
Releated to #3328

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
Do not merge til, Jan.

**Comment by dreddy-work** [comment]
> Do not merge til Jan (this has laready been fixed internally)

What about 6.0?

**Comment by mmitche** [comment]
Same

**Review by ViktorHofer — APPROVED** [review]

**Comment by dreddy-work** [comment]
@mmitche , cna you merge these if it is okay now to merge?

**Comment by mmitche** [comment]
go for it.

**Pull request merged**
