### PR TITLE
[master] Propagate CPD strict for dotnet/sdk

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@AdamYoblick This looks weird...not sure what is going on...

**Comment by dagood** [comment]
That bit of infra is trying to download the VS redist package to grab the MSI, in order to bundle it with the .NET Desktop Runtime installer. Looks like the version number is messed up: `VS.Redist.Common.NetCore.SharedFramework.x86.6.0.`

**Comment by dagood** [comment]
Looks like https://github.com/dotnet/windowsdesktop/commit/2678c6b62b43fa554511552354bc929786199f39 is busted? GitHub doesn't show a PR for it. 😢 

/cc @ryalanms

**Comment by dagood** [comment]
I guess 6.0 forked just now, but not in concert with a dotnet/runtime 6.0 update. That breaks the assumption here that major.minor of dotnet/windowsdesktop will be the same as dotnet/runtime's:

https://github.com/dotnet/windowsdesktop/blob/2678c6b62b43fa554511552354bc929786199f39/pkg/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.Bundle.bundleproj#L33-L37

AFAIK package ids can't be auto-updated so this break isn't avoidable, but it could be made more user-friendly by changing `MajorVersion` to `NETCoreAppMajorVersion` and adding `NETCoreAppMajorVersion` to eng/Versions.props.

/cc @NikolaMilosavljevic

**Comment by mmitche** [comment]
I think what this is doing is assuming that the input major.minor of the runtime matches what is in this repo. This should pass after an initial propagation of dotnet/runtime to windowsdesktop.

**Comment by mmitche** [comment]
Yep. What @dagood said.

**Comment by dagood** [comment]
Your comment is more right though--this will fix itself once an update from dotnet/runtime comes in. This is because the update to 6.0 versioning was pushed directly and bypassed PR validation, so the auto-update contains the second half of the change and will fix CI. Normally you'd have to fixup the dotnet/runtime auto-update PR to get this through.

**Comment by dagood** [comment]
But dotnet/runtime `master` isn't 6.0 yet, so this repo is broken indefinitely. Not sure where coordination went wrong. 😕

**Comment by mmitche** [comment]
The assumption that they will match is probably wrong, but given that runtime should branch soon, I'm not all that concerned about it.

**Comment by dagood** [comment]
Yeah, no functional reason for the assumption AFAIK. I guess the code could do something a bit more complicated like extract the "5.0" from `MicrosoftNETCoreAppRuntimewinx64Version`.

**Pull request merged**
