### PR TITLE
Change PreReleaseVersionLabel to servicing

### PR DESCRIPTION
**Pull request by dkurepa**

### CODE REVIEW

**Comment by dreddy-work** [comment]
@dkurepa / @mmitche , we need https://github.com/dotnet/arcade/pull/8143/files in release/7.0 branch and flow somehow?

**Comment by RussKie** [comment]
@anipik it looks like https://github.com/dotnet/arcade/pull/8143 was never made to the main branch, which means `$(CreatePlatformManifest)` is ignored and this flow isn't failing:

https://github.com/dotnet/windowsdesktop/blob/6a4dd1643aaffc58a76a1aa0280d35ab0315ed50/pkg/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.Ref.sfxproj#L10
https://github.com/dotnet/windowsdesktop/blob/6a4dd1643aaffc58a76a1aa0280d35ab0315ed50/pkg/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.Ref.sfxproj#L76-L78

**Comment by dkurepa** [comment]
The change made it to the main branch https://github.com/dotnet/arcade/pull/11130/files, the problem is I somehow made an error when making the change on the release/7.0 branch. Here's the fix https://github.com/dotnet/arcade/pull/11510. Think we'll have to update arcade after this is merged

**Comment by dreddy-work** [comment]
Thnaks @dkurepa . Please notify us once arcade flow is ready.

**Review by dreddy-work — APPROVED** [review]

**Comment by mmitche** [comment]
It just went through the validation stage, so about an hour.

**Comment by RussKie** [comment]
Thank you folks!

**Pull request merged**
