### PR TITLE
Add channel for '.NET 5 Preview 1'

### PR DESCRIPTION
**Pull request by dagood**
Add a channel mapping for new 5p1 channel. Adding/removing channels are breaking changes for dotnet/windowsdesktop until https://github.com/dotnet/core-setup/pull/8426 and associated PRs are ported to dotnet/windowsdesktop. /cc @mmitche 

I queued and canceled a very basic test build at https://dev.azure.com/dnceng/internal/_build/results?buildId=530465&view=results to see if template is valid.

### CODE REVIEW

**Comment by dagood** [comment]
Filed https://github.com/dotnet/windowsdesktop/issues/533 for the followup to make this not necessary.

**Comment by vatsan-madhavan** [comment]
Will the next update from dotnet/arcade regress this?

**Comment by dagood** [comment]
No, what's being maintained here is a mapping of Arcade channel IDs/names that's used to generate some extra stages in the windowsdesktop build. It's not changing eng/common or anything like that. A similar change will need to be done when new channels are added/removed in the future, unless https://github.com/dotnet/windowsdesktop/issues/533 is done first.

**Comment by dagood** [comment]
Merging to keep `master` in sync with the release branch.

**Pull request merged**
