### PR TITLE
Add dotnet-tools feed to NuGet.config

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This should unblock #801

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
cc: @ViktorHofer

**Comment by jkoritzinsky** [comment]
cc: @dagood for review/merge

**Comment by jkoritzinsky** [comment]
@RussKie can you merge this in for me? I don't have write permissions in this repo.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
