### PR TITLE
Add platform manifest for servicing branch.

### PR DESCRIPTION
**Pull request by dreddy-work**
Adding latest manifest pulled from 7.0.1 SDK installer and inserting into servicing branch.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
Signing off on the _contents_ of the file, though I don't know anything about how/why it's being used in this repo

**Comment by RussKie** [comment]
I don't think this is the complete change.

The checked-in PlatformManifest.txt will only be used is `CreatePlatformManifest` flag is false:
https://github.com/dotnet/windowsdesktop/blob/6a4dd1643aaffc58a76a1aa0280d35ab0315ed50/pkg/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.Ref.sfxproj#L76-L78

And the flag is disabled only for the servicing releases:
https://github.com/dotnet/windowsdesktop/blob/6a4dd1643aaffc58a76a1aa0280d35ab0315ed50/pkg/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.Ref.sfxproj#L10

And we're not in the "servicing" mode:
https://github.com/dotnet/windowsdesktop/blob/6a4dd1643aaffc58a76a1aa0280d35ab0315ed50/eng/Versions.props#L7

**Comment by RussKie** [comment]
Please consider squash-merging.

**Comment by dreddy-work** [comment]
@RussKie , I think we need similar fix like this here:  https://github.com/dotnet/arcade/pull/8143/files .  I am waiting on arcade team to confirm on that. We did this exercise for **7.0.0-test** branch then.

**Comment by RussKie** [comment]
Is there any issue that's tracking the regression in the arcade?

**Pull request merged**
